# Change these first
owner: ifvlaboratory # Your GitHub organization or username, where this repository lives
repo: Service-Monitor # The name of this repository

sites:
  - name: IFVLAB Main server - Transmission
    url: $IFVLAB_MAIN_SERVER_TRANSMISSION_URL
    #method: GET
    expectedStatusCodes:
      - 200
      - 401
  - name: IFVLAB Main server - Vaultwarden
    url: $IFVLAB_MAIN_SERVER_VAULTWARDEN_URL
    #method: GET
  - name: IFVLAB Main server - Syncthing relay
    check: "tcp-ping"
    url: $IFVLAB_MAIN_SERVER_STRELAYSRV_URL
    port: 22070
  - name: IFVLAB Backup server - Transmission
    url: $IFVLAB_BACKUP_SERVER_TRANSMISSION_URL
    #method: GET
    expectedStatusCodes:
      - 200
      - 401
  - name: IFVLAB Backup server - API
    url: $IFVLAB_BACKUP_SERVER_API_URL
    #method: GET
  - name: IFVLAB Backup server - Cloud drive
    url: $IFVLAB_BACKUP_SERVER_DRIVE_URL
    #method: GET
  - name: IFVLAB Backup server - Cloud drive IPv6
    url: $IFVLAB_BACKUP_SERVER_DRIVE_IPV6_URL
    #method: GET

# assignees: 

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ifvlab.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: dark
  name: IFVLAB service status
  introTitle: "**IFVLAB** service status"
  introMessage: Check every 5 minutes.
  navbar:
    - title: Status(Service)
      href: https://status.ifvlab.com
    - title: Status(Server)
      href: https://srvstat.ifvlab.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
